server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: xxxxxx
  mail:
    host: smtp.qq.com
    username: 2274572823@qq.com
    password: xxxxxx
    port: 587
    protocol: smtp
    default-encoding: UTF-8
  redis:
    host: 127.0.0.1
    port: 6379
    password: xxxxxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: xxxxxx
    virtual-host: /  # 默认虚拟主机
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug