---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by think.
--- DateTime: 2024/11/20 22:51
---
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0